### PR TITLE
Use system default timing (easing) function for animation

### PR DESCRIPTION
**Pull request by tfe**
This makes the animation function look a little bit nicer. A more complete implementation would allow using a custom timing function via a property or argument, but this is a nice start.

I would be cautious merging this change though... users of this project might not appreciate the unexpected change in animation style. But on the other hand it's not a huge change and it's pretty clearly superior.

### CODE REVIEW

**Comment by kaandedeoglu** [comment]
Nice! Didn't know about this to be honest. What timing function is used when there's none supplied?

**Comment by tfe** [comment]
I believe it's just linear by default. That's not be confused with `kCAMediaTimingFunctionDefault` which uses the "system default:"

> The system default timing function. Use this function to ensure that the timing of your animations matches that of most system animations.

That's why I figured it was the best one to use here. You can see and try the different curves here: http://netcetera.org/camtf-playground.html.

**Comment by kaandedeoglu** [comment]
Unfortunately this breaks previous behavior, on which many apps rely on. Sadly, I cannot merge this.

**Comment by tfe** [comment]
No worries; thanks for looking at it.

**Pull request closed without merging**
