### PR TITLE
Updated to Swift 4.2

### PR DESCRIPTION
**Pull request by kor45cw**
I changed several things to allow this to work in Swift 4.2

### CODE REVIEW

**Comment by ryanfelton** [comment]
👍

**Comment by kaandedeoglu** [comment]
@kor45cw Looking great! Thanks 👍

**Comment by nithinnizam** [comment]
(Y)

**Comment by ryanfelton** [comment]
Can you create a new release for this change on https://cocoapods.org/pods/KDCircularProgress?

**Comment by kor45cw** [comment]
@kaandedeoglu help!

**Comment by ferrerod** [comment]
Unfortunately there are now **Swift compiler errors** for this Pod after using the latest.

**Comment by nithinnizam** [comment]
Can we have this merge moved to release/ update pod specs? cocoapods still getting version 1.5.2 which doesn't compile in Swift 4.2

**Pull request merged**
